### PR TITLE
Upgrade of the project, add compatibility with Tagger, Journal, Stairway, SoundLink and other features

### PR DESCRIPTION
**Pull request by p4535992**
With this PR I add the possibility to set triggers on the Notes / JournalEntry in the canvas.

The code works, but there is BUG.... to remedy an incompatibility with other modules at the time of the "mouse down" event together with the core setting "Left-Click to Release Object" active, it is necessary that if a token is selected on that event it remains at the event of "mouse up" still selected. 

Unfortunately I have not found any other solution than to temporarily set the "Left-Click to Release Object" setting to false and then reset it to the original state at the "mouse up" event.

Maybe you can find a "smarter" solution.

### CODE REVIEW

**Comment by p4535992** [comment]
Add many new features here the full list:

- Added `@Tag[list of tag separate from ',']` as a filter link to interact with a specific placeable object on the canvas.
- Cleanup code and integrated a better readable workflow for no so smart people like me
- Avoid where possibile to recreate already existent object. Now i try to recover from the canvas/scene/game every object i needed for the trigger instead to create runtime from a wrong id or name, i lose something in performance but i think is the right road to follow
- Add gulp build file for more relaxing build of the source and developing
- Add github action for generate release with 'module.zip' and 'module.json'
- Add integration with Stairways module, limited only to click :(
- Add integration with Tagger mdule (details on readme)
- Made check for entity case insensitive avoid many minor issue form miss typing the name ecc.
- Add the setting 'Enable tagger integration feature' (details on readme)
- Add the setting 'Enable 'journal for every scene' integration feature' (details on readme)
- Add the setting 'Enable 'only use journal for every scene' integration feature' (details on readme)
- Add the setting 'Enable avoid to deselect elements on the trigger event' (details on readme)
- Update README with some cool banner,images and more examples
- Add integration with Sound Link module
- Added `@JournalEntry[id]{label}` as an effect link to interact with note on the canvas.

There is some known issues (check out the [README Known issue paragraph](https://github.com/p4535992/fvtt-module-trigger-happy#known-issue))

Made a bunch of test, but i'm only one guy and i usually made some mistake, here you can download the beta version from my fork for anyone want to help me with some tests . Just install the module using this ref

`https://raw.githubusercontent.com/p4535992/fvtt-module-trigger-happy/master/module-dev.json`

Cheers.

**Comment by tposney** [comment]
I confess to only skimming the commit, but it looks good to me. I'd ask tat over the next couple of weeks you also keep an eye out on the issues list (I noticed you do that anyway) just in case anything new comes about.

**Comment by tposney** [comment]
Do you have a foundry discord handle? So I can properly acknowledge your work?

**Comment by p4535992** [comment]
Discord username: 4535992#1766
Sure you can add me like a collaborator of the github project if you want.
Attention: classic.. the Tagger module version 1.2.1 (10 hour ago) just broke my Tagger integration i will open a new pr this evening after some test

**Comment by tposney** [comment]
You are now added - go for it. And  thanks for the work - it's much appreciated.

**Pull request merged**
