### PR TITLE
Update of the project 

### PR DESCRIPTION
**Pull request by p4535992**
First update of the project in anticipation of further integrations that I hope to implement in the future for integration with other modules like Forien Quest Log, Stairways, hook Macro, Advanced Macro, etc.

Below is a list of the modifications:

- Add prettier
- Add internationalization
- Add more intuitive workflow for the hooks
- Integration of the ecmascript module mechanism
- Update README.md
- Allow tokens to be found by ID (from TheGiddyLimit fork)

### CODE REVIEW

**Review by tposney — COMMENTED** [review]
The fact that you have reformatted the whole module as well as making functional changes means that this is almost impossible to review - without  checking every line. It might as well be a new module of the same name.

I'm tempted to approve and suggest you take over maintenance.

**Comment by p4535992** [comment]
HI @tposney , I'm not that good at managing a project like this on my own, but I can give it a try. I would prefer not to create a new module for the same functionality. If you have no intention of upgrade the project you can put me as a contributor and I will try to work on it.
Greetings.

**Comment by tposney** [comment]
I gave the wrong impression, I delight in assistance. And the more contributors the better. It is just that the way you have created the merge (every line of code is marked as changed - some are just formatting changes and some are fucntional) which means I have to go over every line of code to see what has changed and that will take me a while.

**Comment by tposney** [comment]
And there is no need to create a new project - adding you as a contributor/author is absolutely ok with me. I just have to work out how to do that.

**Comment by p4535992** [comment]
If you think it is better, I can close the PR, reset everything and redo everything, but without the prettier, so git should show better the "different" lines of code

**Comment by tposney** [comment]
I hate to see work wasted. I'll find the time to review the current merge request and then merge it in.

**Pull request merged**
